import './globals.css'
import { Inter } from 'next/font/google'
import HeaderComponent from '@/common/component/header'
import { HEADER_HEIGHT } from '@/common/const'
import FooterComponent from '@/common/component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <HeaderComponent title='pentaclog'/>
      <body style={{width:"100vw",height:"100vh", marginTop:HEADER_HEIGHT, background:"linear-gradient(black,gray)"}} className={inter.className}>{children}</body>
      <FooterComponent/>
    </html>
  )
}
